
#Users

tony = User.create(name: "Tony", password: "michael")
kai = User.create(name: "Kai", password: "michael")
luke = User.create(name: "Luke", password: "michael")
lin = User.create(name: "Lin", password: "michael")

marvel = Publisher.create(name: "Marvel")
dc = Publisher.create(name: "DC")
image = Publisher.create(name: "Image")

detcom = Comic.create(title: "Detective Comics", publisher: dc)
actcom = Comic.create(title: "Action Comics", publisher: dc)
xmen = Comic.create(title: "X-Men", publisher: marvel)
avengers = Comic.create(title: "Avengers", publisher: marvel)
walkdead = Comic.create(title: "The Walking Dead", publisher: image)
invincible = Comic.create(title: "Invincible", publisher: image)

Issue.create(issue_number: 1, comic: detcom)
Issue.create(issue_number: 2, comic: detcom)
Issue.create(issue_number: 3, comic: detcom)
Issue.create(issue_number: 4, comic: detcom)
Issue.create(issue_number: 5, comic: detcom)
Issue.create(issue_number: 6, comic: detcom)
Issue.create(issue_number: 7, comic: detcom)
Issue.create(issue_number: 8, comic: detcom)
Issue.create(issue_number: 9, comic: detcom)
Issue.create(issue_number: 10, comic: detcom)
Issue.create(issue_number: 1, comic: avengers)
Issue.create(issue_number: 2, comic: avengers)
Issue.create(issue_number: 3, comic: avengers)
Issue.create(issue_number: 4, comic: avengers)
Issue.create(issue_number: 5, comic: avengers)
Issue.create(issue_number: 6, comic: avengers)
Issue.create(issue_number: 7, comic: avengers)
Issue.create(issue_number: 8, comic: avengers)
Issue.create(issue_number: 9, comic: avengers)
Issue.create(issue_number: 10, comic: avengers)
Issue.create(issue_number: 1, comic: walkdead)
Issue.create(issue_number: 2, comic: walkdead)
Issue.create(issue_number: 3, comic: walkdead)
Issue.create(issue_number: 4, comic: walkdead)
Issue.create(issue_number: 5, comic: walkdead)
Issue.create(issue_number: 6, comic: walkdead)
Issue.create(issue_number: 7, comic: walkdead)
Issue.create(issue_number: 8, comic: walkdead)
Issue.create(issue_number: 9, comic: walkdead)
Issue.create(issue_number: 10, comic: walkdead)
Issue.create(issue_number: 1, comic: invincible)
Issue.create(issue_number: 2, comic: invincible)
Issue.create(issue_number: 3, comic: invincible)
Issue.create(issue_number: 4, comic: invincible)
Issue.create(issue_number: 5, comic: invincible)
Issue.create(issue_number: 6, comic: invincible)
Issue.create(issue_number: 7, comic: invincible)
Issue.create(issue_number: 8, comic: invincible)
Issue.create(issue_number: 9, comic: invincible)
Issue.create(issue_number: 10, comic: invincible)
Issue.create(issue_number: 1, comic: xmen)
Issue.create(issue_number: 2, comic: xmen)
Issue.create(issue_number: 3, comic: xmen)
Issue.create(issue_number: 4, comic: xmen)
Issue.create(issue_number: 5, comic: xmen)
Issue.create(issue_number: 6, comic: xmen)
Issue.create(issue_number: 7, comic: xmen)
Issue.create(issue_number: 8, comic: xmen)
Issue.create(issue_number: 9, comic: xmen)
Issue.create(issue_number: 10, comic: xmen)
Issue.create(issue_number: 1, comic: actcom)
Issue.create(issue_number: 2, comic: actcom)
Issue.create(issue_number: 3, comic: actcom)
Issue.create(issue_number: 4, comic: actcom)
Issue.create(issue_number: 5, comic: actcom)
Issue.create(issue_number: 6, comic: actcom)
Issue.create(issue_number: 7, comic: actcom)
Issue.create(issue_number: 8, comic: actcom)
Issue.create(issue_number: 9, comic: actcom)
Issue.create(issue_number: 10, comic: actcom)

UserIssue.create(user: tony, issue: Issue.find(1))
UserIssue.create(user: tony, issue: Issue.find(3))
UserIssue.create(user: tony, issue: Issue.find(5))
UserIssue.create(user: tony, issue: Issue.find(11))
UserIssue.create(user: tony, issue: Issue.find(9))
UserIssue.create(user: tony, issue: Issue.find(7))
UserIssue.create(user: tony, issue: Issue.find(10))
UserIssue.create(user: tony, issue: Issue.find(6))
UserIssue.create(user: tony, issue: Issue.find(14))

UserIssue.create(user: kai, issue: Issue.find(2))
UserIssue.create(user: kai, issue: Issue.find(4))
UserIssue.create(user: kai, issue: Issue.find(5))
UserIssue.create(user: kai, issue: Issue.find(6))

UserIssue.create(user: luke, issue: Issue.find(10))
UserIssue.create(user: luke, issue: Issue.find(11))
UserIssue.create(user: luke, issue: Issue.find(12))
UserIssue.create(user: luke, issue: Issue.find(13))

UserIssue.create(user: lin, issue: Issue.find(14))
UserIssue.create(user: lin, issue: Issue.find(17))
UserIssue.create(user: lin, issue: Issue.find(20))
UserIssue.create(user: lin, issue: Issue.find(25))
